# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 890)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/flower-tulip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"        border-radius: 10px; \n"
"        border: 2px groove gray;\n"
"        border-style: outset;\n"
"  \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.select_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_image_button.setGeometry(QtCore.QRect(40, 280, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.select_image_button.setFont(font)
        self.select_image_button.setStyleSheet("QPushButton{\n"
"background-color:rgba(139,139,122, 0.6);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ZTL/Downloads/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_image_button.setIcon(icon1)
        self.select_image_button.setObjectName("select_image_button")
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setGeometry(QtCore.QRect(40, 410, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.predict_button.setFont(font)
        self.predict_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(170, 170, 255, 0.6);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ZTL/Downloads/comment-pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predict_button.setIcon(icon2)
        self.predict_button.setObjectName("predict_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(40, 550, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(205, 51, 51, 0.6);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/ZTL/Downloads/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon3)
        self.exit_button.setObjectName("exit_button")
        self.image2predict = QtWidgets.QGraphicsView(self.centralwidget)
        self.image2predict.setGeometry(QtCore.QRect(370, 80, 641, 461))
        self.image2predict.setStyleSheet("QGraphicsView{\n"
"        border-radius: 5px; \n"
"        border: 2px white blueviolet;\n"
"background-color:rgba(255,255,255, 0.5)\n"
"}")
        self.image2predict.setObjectName("image2predict")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(370, 620, 641, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"        border-radius: 5px; \n"
"        border: 2px black blueviolet;\n"
"        border-style: outset;\n"
"        text-align: center\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.sidebar = QtWidgets.QLabel(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 221, 871))
        self.sidebar.setStyleSheet("QLabel{\n"
"background-color:rgba(192, 255, 62, 0.6);\n"
"}")
        self.sidebar.setText("")
        self.sidebar.setObjectName("sidebar")
        self.avatar = QtWidgets.QLabel(self.centralwidget)
        self.avatar.setGeometry(QtCore.QRect(60, 120, 101, 101))
        self.avatar.setStyleSheet("border-image: url(:/image/logo.png);")
        self.avatar.setText("")
        self.avatar.setObjectName("avatar")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -20, 1261, 861))
        self.background.setStyleSheet("border-image: url(:/image/bg.jpg);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 680, 221, 181))
        self.label.setStyleSheet("border-image: url(:/image/pexels-dominika-roseclay-1877920.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 680, 221, 201))
        self.label_2.setStyleSheet("QLabel{\n"
"background-color:rgba(192, 255, 62, 0.7);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 221, 81))
        self.label_3.setStyleSheet("border-image: url(:/image/pexels-min-an-1650035.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 221, 81))
        self.label_4.setStyleSheet("QLabel{\n"
"background-color:rgba(192, 255, 62, 0.7);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1311, 881))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255,0.4);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.mode_button = QtWidgets.QPushButton(self.centralwidget)
        self.mode_button.setGeometry(QtCore.QRect(1150, 600, 70, 70))
        self.mode_button.setMinimumSize(QtCore.QSize(70, 70))
        self.mode_button.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.mode_button.setFont(font)
        self.mode_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(0, 0, 0, 0.6);\n"
"border-radius:35px\n"
"}")
        self.mode_button.setObjectName("mode_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(1150, 510, 70, 70))
        self.clear_button.setMinimumSize(QtCore.QSize(70, 70))
        self.clear_button.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(139, 117, 0, 0.5);\n"
"border-radius:35px\n"
"}")
        self.clear_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/broom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_button.setIcon(icon4)
        self.clear_button.setIconSize(QtCore.QSize(24, 24))
        self.clear_button.setObjectName("clear_button")
        self.background.raise_()
        self.label_5.raise_()
        self.sidebar.raise_()
        self.select_image_button.raise_()
        self.predict_button.raise_()
        self.exit_button.raise_()
        self.textBrowser.raise_()
        self.avatar.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.image2predict.raise_()
        self.mode_button.raise_()
        self.clear_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1260, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "植物预测"))
        self.select_image_button.setText(_translate("MainWindow", " 选择图片"))
        self.predict_button.setText(_translate("MainWindow", " 预测"))
        self.exit_button.setText(_translate("MainWindow", " 退出"))
        self.mode_button.setText(_translate("MainWindow", "🌗"))
import interface_rc
